# Generated by Django 4.2.2 on 2023-06-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-post_time']},
        ),
    ]
